SELECT ID, 
    CASE
        WHEN R < 0.25 THEN 'CRITICAL'
        WHEN R < 0.5 THEN 'HIGH'
        WHEN R < 0.75 THEN 'MEDIUM'
        ELSE 'LOW' END 'COLONY_NAME'
FROM (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS R
        FROM ECOLI_DATA) A
ORDER BY ID