WITH S AS (
    SELECT CODE
    FROM SKILLCODES 
    WHERE NAME IN ('Python', 'C#')
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME 
FROM DEVELOPERS, S
WHERE SKILL_CODE & S.CODE = S.CODE
ORDER BY ID
    