-- 코드를 작성해주세요
SELECT B.YEAR AS YEAR, B.MAX - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID AS ID
FROM ECOLI_DATA A,
    (SELECT MAX(SIZE_OF_COLONY) AS MAX, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA 
    GROUP BY YEAR) B
WHERE YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV;
